# Generated by Django 2.2 on 2021-11-15 18:11

import app_news.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_auto_20211114_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=app_news.utils.GetUUIDName('article_images'), verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Подзаголовок'),
        ),
    ]
