# Generated by Django 2.2 on 2021-11-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0005_article_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
