# Generated by Django 2.2 on 2021-11-14 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('subtitle', models.CharField(default='', max_length=200, verbose_name='Подзаголовок')),
                ('image', models.URLField(verbose_name='Картинка')),
                ('body', models.TextField(verbose_name='Текст новости')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('body', models.CharField(default='Подзаголовок', max_length=600)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='app_news.Article', verbose_name='Новость')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
